In [2]:
import numpy as np

# Sistemas lineales de ecuaciones algebráicas

Consideremos el sistema de m ecuaciones y n incógnitas dado por

$$\begin{align}
f_1(x_1,x_2,&\dots,x_n) =& 0,\\
f_2(x_1,x_2,&\dots,x_n) =& 0,\\
&\dots&\\
f_m(x_1,x_2,&\dots,x_n) =& 0,\\
\end{align}$$

Decimos que este sistema de ecuaciones es un sistema lineal de ecuaciones (algebráicas) si todas las funciones $f_j$ son combinaciones lineales de las variables $x_i$ y solucionar el sistema implica encontrar el conjunto de $x_i$ que cumplen todas las ecuaciones de manera simultanea. En general, un sistema de ecuaciones lineales puede tener una única solución, ninguna solución o una infinidad de soluciones.

Durante esta sesión nos enfocaremos en el caso en el que nuestro sistema de ecuaciones tiene una única solución, lo cual ocurre cuando tenemos la misma cantidad de ecuaciones linealmente independientes y de incognitas. Podemos entonces escribir nuestro sistema como   
   
   
$$\begin{align}
a_{11}x_1 + a_{12}x_2 + &\dots& + a_{1n}x_n = b_1, \\
a_{21}x_1 + a_{22}x_2 + &\dots& + a_{2n}x_n = b_2, \\
&\dots&\\
a_{n1}x_1 + a_{n2}x_2 + &\dots& + a_{nn}x_n = b_n.   \\
\end{align}$$  

Notemos que podemos representar este sistema de ecuaciones en forma matricial como  $$\boldsymbol{\mathrm{M}}\cdot \boldsymbol{\mathrm{x}}= \boldsymbol{\mathrm{b}},$$

con 

$$\boldsymbol{\mathrm{M}} =  \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} \\ a_{21} &a_{22} &\dots &a_{2n} \\ \vdots &\vdots &\ddots &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} \end{pmatrix}, \quad \boldsymbol{\mathrm{x}} = \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix}, \quad \boldsymbol{\mathrm{b}}=\begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix},$$

es decir
  
$$ \begin{pmatrix} a_{11} &a_{12} &\dots &a_{1n} \\ a_{21} &a_{22} &\dots &a_{2n} \\ \vdots &\vdots &\ddots &\vdots \\ a_{n1} &a_{n2} &\dots &a_{nn} \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix} = \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix}. $$



### Repaso de álgebra

Llamamos  **operaciones elementales** a ciertas operaciones que podemos hacer a los renglones de una ecuación matricial sin alterar la igualdad. Estas operaciones son:

- multiplicar por un escalar no nulo,
- sumar a un renglon una combinación lineal de los otros renglones (por ejemplo, solo uno de los renglones multiplicado por una constante),
- intercambiar dos renglones de lugar.

Estas operaciones tienen que realizarse tanto para el renglon de la matriz $\boldsymbol{\mathrm{M}}$ como el renglon correspondiente del vector $\boldsymbol{\mathrm{b}}$

Usaremos un conjunto de estas operaciones elementales para obtener la solución de nuestro sistema mediante el método de eliminación Gaussiana que recordarán de sus clases álgebra de los primeros semestres.

##### Ejercicio 1 (no es de programar)

Muestra que las operaciones elementales mantienen la igualdad de la ecuación matricial.

### Método de eliminación Gaussiana

Buscamos, a través de operaciones elementales, transformar un sistema lineal de ecuaciones algebráicas en otro de la forma

$$ \begin{pmatrix} a'_{11} &a'_{12} &\dots &a'_{1n} \\ 0 &a'_{22} &\dots &a'_{2n} \\ \vdots &\vdots &\ddots &\vdots \\ 0 & 0 &\dots &a'_{nn} \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix} = \begin{pmatrix} b'_1 \\ b'_2 \\ \vdots \\ b'_n \end{pmatrix}, $$


con $a'_{ij}\neq0$ para $i\leq j\leq n$ y $a'_{ij}=0$ en cualquier otro caso. A una matriz como la de la relación anterior, se le llama **triangular superior**. Como la última ecuación de este nuevo sistema tiene sólo una incógnita, es sencillo despejar, obteniendo

$$x_n = \frac{b'_n}{a'_{nn}}.$$

Entonces para el penúltimo renglón tenemos que

$$a'_{n-1,n-1} \cdot x_{n_1} + a'_{n-1,n} \cdot x_{n}=b'_{n-1}$$

##### Ejercicio 2 (tampoco es de programar)

Despeja a $x_{n-1}$ de la penúltima ecuación de manera que quede en términos de $x_n$. Realiza lo mismo para el resto de las $x_i$ ($i<n$) de manera que obtengas una expresión para $x_i$ en términos de las todas las $x_j$ ($j>i$). Demuestra que esta expresión es igual a:

\begin{equation}
x_i=\frac{1}{a'_{ii}}\left( b'_{i}-\sum\limits_{j>i} a'_{ij} \cdot x_{j} \right ).
\end{equation}


Nota que esta expresión depende de $a'_{ii},...,a'_{in}$ y de $b_i$.

## Preámbulo: matrices en python usando numpy

Usando numpy es posible definir areglos de areglos que de manera efectiva nos permiten representar matrices. Estos arreglos de arreglos (un arreglo de numpy de dos dimensiones) admiten operaciones vectorizadas además de indexación por lo que su uso es muy similar al de los vectores que hemos estado usando hasta ahora.

In [21]:
M = np.array( [[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
x=np.array([1,10,100])
x

array([  1,  10, 100])

In [23]:
M*x

array([[  1,  20, 300],
       [  4,  50, 600],
       [  7,  80, 900]])

In [24]:
M.dot(x)

array([321, 654, 987])

In [25]:
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
A=M
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
M[0,0]=100
M,A

(array([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]),
 array([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]))

In [28]:
A=M.copy()
A

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [29]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.random.rand(3,3)

array([[0.71149961, 0.99976204, 0.05427899],
       [0.93179   , 0.07859321, 0.96063282],
       [0.16435257, 0.23594422, 0.38571603]])

In [49]:
D=np.reshape(np.arange(9),(3,3))
D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
D.mean(axis=0)

array([3., 4., 5.])

En general, pueden hacer areglos de arreglos de arreglos de ... de arreglos. Si ese es un arreglo de numpy, obtenemos lo que en su más burda definición llamariamos un tensor (al menos en estructura).

##### Ejercicio 3

Implementa una función `sol_trisup(A,b)` que tome como argumento un arreglo 2D (un arreglo de arreglos) `A`, que representa a una matriz **triangular superior, sin ceros en la diagonal**, de $n\times n$ , un vector solución `b` de longitud $n$ y que regresa un arreglo `xx` con la solución del sistema $\mathbf{A}\cdot\mathbf{x} = \mathbf{b}$ calculada usando la fórmula del ejercicio anterior. **Nota:** recuerda que la fórmula del ejercicio anterior dice que $x_i$ depende de los valores de $x_j$ con $j>i$, por lo que deberás calcular las $x_i$ en un orden específico.

In [174]:
def sol_trisip(A,b):
    M=np.append(A.T,[[b[i] for i in range(len(b))]],axis=0).T
    c=len(M[0])-1
    f=len(M)-1
    
    M[f,c]=M[f,c]/M[f,c-1] #Primera retropropagación
    
    R=0.0
    
    for j in reversed(range(f,0)):
        for i in range(j,f):
           R=R+M[i+1,c]*M[j,i+1] #Sumas de sustituciones anteriores
    
        if M[j,j]!=0:
            M[j,c]=(M[j,c]-R)/M[j,j] #Despeje de incógnitas
            R=0.0
        else:
            continue
    
    return M

In [175]:
A=np.array([[3,1,-5],[0,-2,4],[0,0,2]])
b=np.array([1,10,6])

sol_trisip(A,b)

array([[ 3,  1, -5,  1],
       [ 0, -2,  4, 10],
       [ 0,  0,  2,  3]])

In [169]:
for i in reversed(range(1,3+1)):
    print(i)

3
2
1


Aquí les dejo un par de ejemplos para que prueben su función `sol_trisup`

##### Ejemplo 1

$$
\begin{pmatrix}
3 & 1 & -5 \\
0 & -2 & 4 \\
0 & 0 & 2 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
\end{pmatrix} 
=
\begin{pmatrix}
1 \\
10 \\
6 \\
\end{pmatrix} 
$$

Solución: $x=5$, $y=1$, $z = 3$

##### Ejemplo 2

$$
\begin{pmatrix}
3 & -2 & 1 & -1 \\
0 & 4 & -1 & 2 \\
0 & 0 & 2 & 3 \\
0 & 0 & 0 & 5 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
w \\
\end{pmatrix} 
=
\begin{pmatrix}
8 \\
-3 \\
11 \\
15 \\
\end{pmatrix} 
$$

Solucion: $x=2$, $y=-2$, $z=1$,  $w=3$



Muy lindo y todo, pero nuestra funcón nos permite solucionar solo problemas en los que la matriz es triangular superior. Cómo hacemos para resolver un sistema arbitrario? Lo primero que se nos puede ocurrir es si podemos pasar de un sistema arbitrario a uno con representación matricial mediante una cantidad finíta de operaciones elementales (por eso las vimos al inicio :P).

## ¿Cómo volver una matriz cualquiera en una matriz diagonal superior?

### La matriz aumentada

Llamamos **matriz aumentada** y la denotadamos por $\mathbf{C}$, a la matriz que obtenemos al añadir el vector solución $\mathbf{b}$ como una columna adicional a la matriz $\mathbf{M}$ de un sistema de ecuaciones,

$$
\mathbf{C} = 
\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} & b_1 \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} & b_2 \\
  \vdots  &   & \ddots &   & \vdots \\
  a_{n,1} & a_{n,2} & \cdots & a_{n,n} & b_n 
 \end{pmatrix} 
 $$

Mediante operaciones elementales de renglones (intercambiar renglones, multiplicarlos por un escalar o sumarlos), buscamos reducir la matriz $\mathbf{C}$ a una forma **escalonada**, denotada $\mathbf{C}^*$, en la que todos los elementos por debajo de la diagonal sean $0$:

$$
\mathbf{C}^* = 
\begin{pmatrix}
  a^*_{1,1} & a^*_{1,2} & \cdots & a^*_{1,n} & b^*_1 \\
  0 & a^*_{2,2} & \cdots & a^*_{2,n} & b^*_2 \\
  \vdots  &   & \ddots &   & \vdots \\
  0 & 0 & \cdots & a^*_{n,n} & b^*_n 
 \end{pmatrix} 
 $$
 
 Esa matriz aumenta representa al sistema de ecuaciones:
 
 $$
\begin{pmatrix}
  a^*_{1,1} & a^*_{1,2} & \cdots & a^*_{1,n} \\
  0 & a^*_{2,2} & \cdots & a^*_{2,n} \\
  \vdots  &   & \ddots &   \vdots \\
  0 & 0 & \cdots & a^*_{n,n} 
 \end{pmatrix} 
 \begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n 
 \end{pmatrix}=
 \begin{pmatrix}
b^*_1 \\
b^*_2 \\
\vdots \\
b^*_n 
 \end{pmatrix}
 $$
 

El sistema de ecuaciones representado por $\mathbf{C}^*$ es equivalente al representado por $\mathbf{C}$, por lo que sus soluciones son las mismas. Sin embargo, el sistema asociado a la matriz escalonada es triangular superior, por lo que es mucho más fácil de resolver, como vimos en los ejercicios anteriores.

## Preámbulo 2: Extender un arreglo de numpy

In [50]:
pr2 = np.array([1,2,3])
pr2

array([1, 2, 3])

In [51]:
pr2.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [52]:
np.append(pr2,4)

array([1, 2, 3, 4])

In [60]:
pr3=np.reshape(np.arange(16),(4,4))
pr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.append(pr3,[[1,1,1,1]],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 1,  1,  1,  1]])

In [63]:
np.append(pr3.T,[[1,1,1,1]],axis=0).T

array([[ 0,  1,  2,  3,  1],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  1],
       [12, 13, 14, 15,  1]])

##### Ejercicio 4 (no es de programar)

(i) Supón que $a_{1,1} \neq 0$. ¿Qué operación elemental podrías aplicarle al renglón $n$ para hacer que el elemento $a_{n,1}$ se vuelva 0?

**Sugerencia** La operación es convertir al renglón $n$ en una combinación lineal del renglón $1$ y el renglón $n$

(ii) ¿Puedes aplicar el procedimiento un procedimiento similar al del inciso anterior pero ahora para hacer $a_{n-1,1}=0$? ¿y para cualquier otro $a_{k,1}=0$ con $k \neq 1$?

(iii) Vamos ahora a la segunda columna. Supón que ya realizaste todas las operaciones elementales necesarias para que $a_{k,1} =0$ para $k \neq 1$. Nuevamente suponiendo que $a_{2,2}\neq 0$, ¿cómo puedes hacer algo parecido a las operaciones elementales de los incisos anteriores para volver $a_{k,2} =0$ para $k \neq 2$?

(iv) Generaliza todo lo visto anteriormente para encontrar las operaciones elementales necesarias (y el orden de ellas) para convertir a la matriz aumentada $\mathbf{C}$ en la matriz escalonada $\mathbf{C}^*$.


##### Ejercicio 5

Implementa una función `elim_gauss_chafa(A,b)` que toma como argumento un arreglo bidimensional (arreglo de arreglos) `M` de $n\times n$ **suponiendo que no tiene ceros en la diagonal** y un arreglo unidimensional `b` de longitud $n$. La función debe de construir la matriz aumentada $\mathbf{C}$ obtenida a partir de `A` y `b` y luego realizar las operaciones elementales obtenidas en el ejercicio anterior para generar la matriz escalonada $\mathbf{C}^*$. La función debe de regresar la matriz escalonada obtenida, que va a ser de $n\times (n+1)$.


Aquí unos ejemplos para que prueben su `elim_gauss`

##### Ejemplo 1

$$
\begin{pmatrix}
1 & 1 & 1 \\
1 & 2 & 4 \\
1 & 3 & 9 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
\end{pmatrix} 
=
\begin{pmatrix}
1 \\
-1 \\
1 \\
\end{pmatrix} 
$$

Se convierte en

$$
\begin{pmatrix}
1 & 1 & 1 \\
0 & 1 & 3 \\
0 & 0 & 2 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
\end{pmatrix} 
=
\begin{pmatrix}
1 \\
-2 \\
4 \\
\end{pmatrix} 
$$

##### Ejemplo 2

$$
\begin{pmatrix}
4 & 8 & 4 & 0 \\
1 & 5 & 4 & -3 \\
1 & 4 & 7 & 2 \\
1 & 3 & 0 & -2 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
w \\
\end{pmatrix} 
=
\begin{pmatrix}
8 \\
-4 \\
10 \\
-4 \\
\end{pmatrix} 
$$

se convierte en 

$$
\begin{pmatrix}
4 & 8 & 4 & 0 \\
0 & 3 & 3 & -3 \\
0 & 0 & 4 & 4 \\
0 & 0 & 0 & 1 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
w \\
\end{pmatrix} 
=
\begin{pmatrix}
8 \\
-6 \\
12 \\
2 \\
\end{pmatrix} 
$$

## ¿Qué sucede si hay elementos $a_{ii}=0$?

Es fundamental que los elementos de la diagonal no sean $0$ para que nuestro método funcione. Sin embargo, es posible que se de el caso en el esto no suceda. Si $a_{k,k}=0$, podemos buscar un renglón $l$ en el que $a_{l,k}\neq 0 $ y luego **intercambiar** el renglón $k$ por el $l$.

Debido a que estamos suponiendo que la solución al sistema es única, no puede nunca darse el caso de $a_{l,k}=0$ para toda $l$ pues eso implicaría que no existe solución única para el sistema. Eso garantiza que siempre existirá un renglón que podamos intercambiar.

Sin embargo, notemos que el cambio no puede darse de manera tan simple, pues si el renglón $k$ que cumple que $a_{k,l} = 0$ entonces, al cambiar $k$ por $l$, eso pondrá un cero en el elemento $l$ de la diagonal.

##### Ejercicio 6

Implementa una función `matrizC(A,b)` que toma como argumento un arreglo 2D `A` de $n\times n$ y un arreglo 1D `b` de longitud $n$. La función debe de construir la matriz aumentada $\mathbf{C}$ obtenida a partir de `A` y `b` y luego revisar sus elementos diagonales para ver que no sean $0$. Si encuentra alguno que sea $0$, debe de intercambiar el renglón por otro en el que sea distinto de cero. La función debe de regresar una matriz aumentada  en la que no haya ceros en las diagonales. Revisa que tu función funcione usando un ejemplo sencillo de una matriz de $3\times3$ (ponle ceros en la diagonal para que estés seguro de que lo hace bien).

Rescatemos todo lo que hemos hecho hasta ahora para al fin escribir nuestra función de eliminación gaussiana que tomo un caso general. Para ello usaremos la función `matrizC` del ejercicio anterior.  
<br>

##### Ejercicio 7

Implementa una función `elim_gauss(A,b)` que toma como argumento un arreglo 2D `A` de $n\times n$ y un arreglo 1D `b` de longitud $n$. La función primero debe de usar `checarDiagonal(A,b)` para obtener una matriz aumentada sin ceros en las diagonales y luego debe de aplicar las operaciones elementales del ejercicio 3 para obtener una matriz escalonada $\mathbf{C}^*$. La función debe de regresar dicha matriz escalonada de $n\times (n+1)$.

##### Ejercicio 8

Implementa una función `solSEL(A,b)` que toma como argumento un arreglo 2D `A` de $n\times n$  y un arreglo 1D `b` de longitud $n$. Tu función debe de utilizar las funciones `elim_gauss` y `sol_trisup` para resolver el sistema de ecuaciones lineales y regresar un arreglo 1D de longitud $n$ correspondiente a las soluciones $x_i$. _**Hint**_: `elim_gauss` regresa a la matriz $\mathbf{C}$ que luego debes partir en una matriz $\mathbf{A}'$ y un vector solución $\mathbf{b}'$ y eso es lo que se come `sol_trisup`.


##### Ejercicio 9

Prueba tu función `solSEL(A,b)` para los siguientes sistemas:

i) El sistema 

$$\begin{cases}5x-3y-z=1 \\ x+4y-6z=-1 \\ 2x+3y+4z=9 \end{cases},$$

con representación matricial
$$
\begin{pmatrix}
5 & -3 & -1 \\
1 & 4 & -6 \\
2 & 3 & 4 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
\end{pmatrix} 
=
\begin{pmatrix}
1 \\
-1 \\
9 \\
\end{pmatrix}.
$$

Solución: $x=1$, $y=1$, $z = 1$  

<br>
ii) El sistema 
$$\begin{cases}x + 5y - z + w & = & -6 \\ x + y + z + w & = & 0 \\ 2x - 2y + z - w & = & 7 \\ x -6y - 3z + 2w & = & -4 \end{cases},$$

con repesentación matricial
$$
\begin{pmatrix}
1 & 5 & -1 & 1 \\
1 & 1 & 1 & 1 \\
2 & -2 & 1 & -1 \\
1 & -6 & -3 & 2 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
w \\
\end{pmatrix} 
=
\begin{pmatrix}
-6 \\
0 \\
7 \\
-4 \\
\end{pmatrix}.
$$

Solucion: $x=1$, $y=-2/3$, $z=5/3$,  $w=-2$