#  Tarea 04. Álgebra

Desafortunadamente y por el tiempo que queda del curso, la implementación "desde cero" para resolver sistemas de ecuaciones lineales que quedaría como tarea 04 ya no lo será. En lugar de ello, si así lo deciden, pueden entregar el notebook "06. Sistemas de ecuaciones lineales" como tarea extra. Esto contará como reposición de tarea. Para ello tienen hasta la semana de presentación de proyectos. En su lugar, en este notebook hay un ejercicio que utiliza numpy para resolver sistemas de ecuaciones lineales.

________

##### Ejercicio 1


i) Revisa la documentación de la función `np.linalg.solve` para que veas que hace. Básicamente, toma como argumentos una matriz y un vector asociados a un sistema de ecuaciones lineales y regresa un vector con las soluciones. Utiliza esta función para resolver los siguientes sistemas de ecuaciones lineales. Cerciorate de que encuentras la solución correcta.

1) El sistema 

$$\begin{cases}5x-3y-z=1 \\ x+4y-6z=-1 \\ 2x+3y+4z=9 \end{cases},$$

con representación matricial
$$
\begin{pmatrix}
5 & -3 & -1 \\
1 & 4 & -6 \\
2 & 3 & 4 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
\end{pmatrix} 
=
\begin{pmatrix}
1 \\
-1 \\
9 \\
\end{pmatrix}.
$$

Solución: $x=1$, $y=1$, $z = 1$  

<br>
2) El sistema 
$$\begin{cases}x + 5y - z + w & = & -6 \\ x + y + z + w & = & 0 \\ 2x - 2y + z - w & = & 7 \\ x -6y - 3z + 2w & = & -4 \end{cases},$$

con repesentación matricial
$$
\begin{pmatrix}
1 & 5 & -1 & 1 \\
1 & 1 & 1 & 1 \\
2 & -2 & 1 & -1 \\
1 & -6 & -3 & 2 \\
\end{pmatrix} 
\begin{pmatrix}
x \\
y \\
z \\
w \\
\end{pmatrix} 
=
\begin{pmatrix}
-6 \\
0 \\
7 \\
-4 \\
\end{pmatrix}.
$$

Solucion: $x=1$, $y=-2/3$, $z=5/3$,  $w=-2$

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [31]:
#1)

A1 = np.array([[5,-3,-1],[1,4,-6],[2,3,4]])
b1 = np.array([1,-1,9])

np.linalg.solve(A1,b1)

array([1., 1., 1.])

In [40]:
#2)

A2 = np.array([[1,5,-1,1],[1,1,1,1],[2,-2,1,-1],[1,-6,-3,2]])
b2 = np.array([-6,0,7,-4])

np.linalg.solve(A2,b2)

array([ 1.        , -0.66666667,  1.66666667, -2.        ])

Probemos otra forma de resolver sistemas de ecuaciones. Recordemos que un sistema de ecuaciones lineales representado por $\mathbf{A}\cdot\mathbf{x} = \mathbf{b}$ puede tener una, ninguna o una infinidad de soluciones.

ii) ¿Qué condición debe tener el determinante de $\mathbf{A}$ para que exista una única solución? (no es de programar)

Sea $\mathbf{A} \in \mathcal{M}_{n \times n}$, si $\det(\mathbf{A}) \neq 0$ entonces $\mathbf{A}\cdot\mathbf{x} = \mathbf{b}$ tiene solución única.

Notemos que cuando esta condición se cumple podemos escribir $\mathbf{x} = \mathbf{A}^{-1}\cdot\mathbf{b}$ con $\mathbf{A}^{-1}$ la matriz inversa de $\mathbf{A}$ y así entonces

\begin{align}
\mathbf{A}^{-1} \cdot \mathbf{A} \cdot \mathbf{x} = \mathbf{A}^{-1} \cdot \mathbf{b} 
\Rightarrow \mathbb{I} \cdot \mathbf{x} = \mathbf{A}^{-1} \cdot \mathbf{b}
\Rightarrow \mathbf{x} = \mathbf{A}^{-1} \cdot \mathbf{b}
\end{align}

iii) Revisa la documentación de la función `np.linalg.inv` y úsala para encontrar la solución de los mismos sistemas de ecuaciones del inciso i).

In [46]:
#1)

np.dot(np.linalg.inv(A1),b1)

array([1., 1., 1.])

In [47]:
#2)

np.dot(np.linalg.inv(A2),b2)

array([ 1.        , -0.66666667,  1.66666667, -2.        ])

_________

#### Ejercicio extra: Vale por un ejercicio extra pero no por un problema (no es de programar)

Sea $\mathbf{M}$ una matriz real y simétrica de $n \times n$ con valores y vectores propios $\lambda_1, \ldots, \lambda_n$ y $\mathbf{v}_{p,1}, \ldots, \mathbf{v}_{p,n}$ tales que $ |\lambda_1| \leq |\lambda_2| \leq  \ldots \leq |\lambda_n|$.

Utiliza el **[teorema espectral](https://en.wikipedia.org/wiki/Spectral_theorem)** para demostrar que la matriz $\mathbf{B}_k (\mathbf{M})$, definida como

$$
\mathbf{B}_k (\mathbf{M}) = \mathbf{M} - \frac{\lambda_k}{\Vert \mathbf{v}_{p,k} \Vert^2}\mathbf{v}_{p,k}^T \mathbf{v}_{p,k},
$$

tiene valores propios $\lambda_k = 0,\lambda_1,\ldots,\lambda_{k-1},\lambda_{k+1},\ldots,\lambda_n$ y sus correspondientes vectores propios asociados son $\mathbf{v}_{p,k},\mathbf{v}_{p,1},\ldots,\mathbf{v}_{p,k-1}, \mathbf{v}_{p,k+1},\ldots,\mathbf{v}_n$. Es decir, la matriz $\mathbf{B}_k$ tiene los mismos valores propios y vectores propios de $\mathbf{M}$ excepto por $\lambda_k$ que ahora es cero.

**_Hint_**: recuerda que
$$
\mathbf{v}^T \mathbf{w} = \begin{pmatrix}
v_1 w_1 & v_1 w_2 & \ldots & v_1 w_n \\
v_2 w_1 & v_2 w_2 & \ldots & v_2 w_n \\
\vdots & \vdots & \ddots & \vdots \\
v_n w_1 & v_n w_2 & \ldots & v_n w_n \\
\end{pmatrix}
$$

Y que  $(\mathbf{v}^T \mathbf{w}) \mathbf{u} = (\mathbf{w} \cdot \mathbf{u}) \mathbf{v}^T.  $ 

___________

#### Ejercicio 2

Repite el ejercicio 4 del notebook "07. Vectores y valores propios" usando la `np.linalg.eig`. Lee la documentación para saber cómo se usa esta función. Comprueba que tus soluciones son correctas comprobando que $\mathbf{M} \cdot \mathbf{v}_p = \lambda \, \mathbf{v}_p$ 

In [98]:
#1)

M1 = np.array([[5,0],[0,3]])

l1,v1 = np.linalg.eig(M1)

l1,v1,np.dot(M1,v1),l1*v1

(array([5., 3.]),
 array([[1., 0.],
        [0., 1.]]),
 array([[5., 0.],
        [0., 3.]]),
 array([[5., 0.],
        [0., 3.]]))

In [110]:
#2)

M2 = np.array([[1,2,3],[2,1,4],[3,4,1]])

l2,v2 = np.linalg.eig(M2)

l2,v2,np.round(np.dot(M2,v2),12)==np.round(l2*v2,12) #Redondeado a 12 decimales para comprobar la igualdad

(array([ 7.07467358, -0.88679099, -3.1878826 ]),
 array([[ 0.50578521,  0.82403773, -0.25523155],
        [ 0.58437383, -0.54492509, -0.60130182],
        [ 0.63457746, -0.15497893,  0.75716113]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

In [112]:
#3)

M3 = np.array([[2,0,4,0],[0,1,3,5],[4,3,5,7],[0,5,7,3]])

l3,v3 = np.linalg.eig(M3)

l3,v3,np.round(np.dot(M3,v3),12)==np.round(l3*v3,12) #Redondeado a 12 decimales para comprobar la igualdad

(array([14.15753708,  3.3443981 , -4.70725818, -1.794677  ]),
 array([[ 0.22195176,  0.80218821, -0.31997168, -0.45260315],
        [ 0.37922193, -0.401573  ,  0.33564845, -0.76306616],
        [ 0.67459667,  0.26961508,  0.53653317,  0.42937069],
        [ 0.59316732, -0.35005844, -0.70504638,  0.16888227]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

_________

#### Problema 1: osciladores armónicos acoplados

Considera el sistema de dos carros de masas $m_1$ y $m_2$, acoplados entre si y a dos paredes por tres resortes Hookeanos (que siguen la ley de Hooke) con constantes $k_1$, $k_2$ y $k_3$. El siguiente diagrama representa al sistema:

<div>
<img src="https://d2vlcm61l7u1fs.cloudfront.net/media%2F146%2F146c6723-0056-4cb5-8b20-dc4eccefd526%2FphpM4if1A.png" width="500"/>
</div>

La solución de este sistema está dada por las ecuaciones

$$
\begin{align}
x_1(t) &= \alpha_1 \cos{(\omega t - \delta_1)} \\
x_2(t) &= \alpha_2 \cos{(\omega t - \delta_2)},
\end{align}
$$

con $x_1(t)$ y $x_2(t)$ los desplazamientos de cada carrito respecto a sus posiciones de equilibrio.  


Supongamos que los carros son de masas iguales $m_1 = m_2 = m$ y que $\delta_1 = \delta_2 = 0$. Así, la frecuencia $\omega$ y el vector de amplitudes $\mathbf{A} = [\alpha_1, \alpha_2]$ se puede encontrar de la siguiente manera:

$\mathbf{A}$ es un vector propio, y $m \omega^2$  su valor propio asociado, de la **matriz de constante de resortes** $\mathbf{K}$, definida como

$$
\mathbf{K} = \begin{pmatrix}
k_1 + k_2 & -k_2 \\
-k_2 & k_2 + k_3 \\
\end{pmatrix}
$$

Notemos que, por ser simétrica, la matriz $\mathbf{K} $ tendrá dos  vectores propios distintos, asociados a valores propios distintos. Cada uno de ellos define dos movimientos distintos de los carros acoplados que corresponden a sus **modos normales**.


i) Utilizando la función `np.linalg.eig`, escribe una función `carrosAcoplados(k1,k2,k3,m)` que tome como argumento los valores de las constantes $k_1$, $k_2$, $k_3$ y de la masa $m$ y que regrese las dos frecuencias $\omega_1, \omega_2$ y sus vectores de amplitudes correspondientes $\mathbf{A}_1, \mathbf{A}_2$.

Revisa que para el caso $k_1=k_2=k_3=k$, se cumpla

$$
\omega_1 = \sqrt{\frac{k}{m}} \quad , \quad \mathbf{A}_1 = \frac{1}{\sqrt{2}} (1,1)
$$

$$
\omega_2 = \sqrt{\frac{3k}{m}} \quad , \quad \mathbf{A}_2 = \frac{1}{\sqrt{2}} (1,-1)
$$

**Sugerencia**: para comprobar que se cumplen esas relaciones, deberán darle valores arbitrarios a $k$ y $m$

In [118]:
def carrosAcoplados(k1,k2,k3,m):
    K=np.array([[k1+k2,-k2],[-k2,k2+k3]])
    l,A = np.linalg.eig(K)
    ω = np.sqrt(l/m)
    return ω,A

Sea $k_1=k_2=k_3=k=4$ y $m=1$ entonces analíticamente

$$
\omega_1 = \sqrt{4} = 2 \quad , \quad \mathbf{A}_1 = \frac{1}{\sqrt{2}} (1,1) = (0.70710,0.70710)
$$

$$
\omega_2 = \sqrt{3 \times 4} = \sqrt{12} = 3.4641 \quad , \quad \mathbf{A}_2 = \frac{1}{\sqrt{2}}(1,-1) = (0.70710,-0.70710)
$$

y usando la función `carrosAcoplados` se tiene

In [119]:
carrosAcoplados(4,4,4,1)

(array([3.46410162, 2.        ]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

Lo cual coincide con el resultado analítico.